[build]
 functions = "netlify/functions/"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "chrome-aws-lambda", "import-fresh"]

[[redirects]]
from = "/"
to = "/.netlify/functions/lunchHr"
status = "200"